version: "3.9"

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 30s
      retries: 60

  emulator:
    image: devopsifyme/sbemu:latest
    environment:
      - EMULATOR__RABBITMQ__HOST=rabbit
      - EMULATOR__RABBITMQ__USERNAME=guest
      - EMULATOR__RABBITMQ__PASSWORD=guest
    ports:
      - "5671:5671"
    links:
      - rabbit
    depends_on:
      rabbit:
        condition: service_healthy
